### ISSUE TITLE
Don't run, just build

### ISSUE THREAD

**Issue by jwhitcraft** [William-Olson/go-watch#1]
It would be awesome to just have it build when a go-file is changed, instead of building and then running.  I need to run my program in the context of a git dir, so just running it by itself does me no good.

Thanks.

**Comment by William-Olson** [comment]
I think I can add that pretty easily.  I am at school right now but will take a look once I get home tonight.

Maybe just check if no `-r` flag is given, if so then don't run. Something like that.

**Comment by William-Olson** [comment]
Added this in version 0.1.0 as described above (just omit the `-r` flag to not run the binary).
